### ISSUE TITLE
Crash on iPad Mini 5 A12 on iPadOS 14.3 RC 1

### ISSUE THREAD

**Issue by slavicweebofficial** [brandonplank/PlankFilza#1]
PlankFilza crashes my iPad way too much causing it to reboot every time it happens after clicking OK when I receive the message "Main binary was modified. Please reinstall Filza", closing the app from the app switcher and sometimes randomly.
![B015F1A4-8734-4724-8569-AD99C021CE1F](https://user-images.githubusercontent.com/63901383/107920384-f2cc4300-6f7d-11eb-9fc4-c8ced338ac2b.png)

**Comment by hazefreak1** [comment]
Same error on my iPhone X with iOS 14.3
